# Generated by Django 5.0.4 on 2024-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='1', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
