# Generated by Django 5.0.4 on 2024-04-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='store',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
