# Generated by Django 5.0.4 on 2024-04-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_order_seller_alter_user_name_alter_user_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.CharField(max_length=20),
        ),
    ]
