# Generated by Django 5.0.4 on 2024-04-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_product_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimg',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
